Trackgenre:
    type: entity
    table: tx_digitaldjpool_domain_model_trackgenre
    indexes:
        parent:
            columns:
                - pid
        t3ver_oid:
            columns:
                - t3ver_oid
                - t3ver_wsid
        language:
            columns:
                - l10n_parent
                - sys_language_uid
    id:
        uid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    fields:
        pid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
        name:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
        tstamp:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
        crdate:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
        cruserId:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
            column: cruser_id
        deleted:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        hidden:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
        starttime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
        endtime:
            type: integer
            nullable: false
            unsigned: true
            comment: ''
            default: '0'
        t3verOid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_oid
        t3verId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_id
        t3verWsid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_wsid
        t3verLabel:
            type: string
            nullable: false
            length: 255
            fixed: false
            comment: ''
            default: ''
            column: t3ver_label
        t3verState:
            type: boolean
            nullable: false
            comment: ''
            default: '0'
            column: t3ver_state
        t3verStage:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_stage
        t3verCount:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_count
        t3verTstamp:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_tstamp
        t3verMoveId:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: t3ver_move_id
        sysLanguageUid:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: sys_language_uid
        l10nParent:
            type: integer
            nullable: false
            unsigned: false
            comment: ''
            default: '0'
            column: l10n_parent
        l10nDiffsource:
            type: blob
            nullable: true
            length: null
            fixed: false
            comment: ''
            column: l10n_diffsource
    lifecycleCallbacks: {  }
