<?php

namespace Cpyree\SynologyBundle\Webapi;

use Cpyree\SynologyBundle\Services\SynologySession;

class SearchStartSynoRequest extends WebApiRequest{

	private $searchPattern;
	private $searchPath;

    /**
     * @param SynologySession $session
     * @return $this
     * @throws Exception
     */
    public function setSession(SynologySession $session)
    {
        parent::setSession($session); // TODO: Change the autogenerated stub
        $this->setApiName('SYNO.FileStation.Search');
        return $this;
    }

    public function setSearchPattern($searchPattern){
		$this->searchPattern = $searchPattern;
		return $this;
	}
	public function getSearchPattern(){
		return $this->searchPattern;
	}

	/**
	 * @param $searchPath
	 * @return $this
	 */
	public function setSearchPath($searchPath)
	{
		$this->searchPath = $searchPath;
		return $this;
	}

	/**
	 * @return mixed
	 */
	public function getSearchPath()
	{
		return $this->searchPath;
	}

	/**
	 * @param $path
	 * @param $pattern
	 * @return $this
	 */
	public function search($path, $pattern){
		$this->setSearchPath($path)->setSearchPattern($pattern);
		return $this;
	}

	/**
	 * @return SynoResponse
	 */
	public function send(){
		$this
			->setMethod('start')
			->addParam('folder_path', $this->getSearchPath())
			->addParam('pattern',$this->getSearchPattern());
		return parent::send();
	}


}
