<?php
/**
 * Created by PhpStorm.
 * User: christophep
 * Date: 15/11/2014
 * Time: 21:31
 */

namespace Cpyree\AdminLTEBundle\Form\Type;


use Cpyree\AdminLTEBundle\Form\DataTransformer\DateRangeToStringTransformer;
use Symfony\Component\Form\AbstractType;
use Cpyree\AdminLTEBundle\Form\DataTransformer\RangeToStringTransformer;
use Symfony\Component\Form\AbstractTypeExtension;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\Form\FormInterface;
use Symfony\Component\Form\FormView;
use Symfony\Component\OptionsResolver\OptionsResolverInterface;

class DateRangeType extends AbstractType{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $dateRangeToStringTransformer = new DateRangeToStringTransformer();
        $builder->addModelTransformer($dateRangeToStringTransformer);
    }


    /**
     * {@inheritdoc}
     */
    public function setDefaultOptions(OptionsResolverInterface $resolver)
    {
        parent::setDefaultOptions($resolver); // TODO: Change the autogenerated stub
        $resolver->setDefaults(array(
            'format'    =>  'timestamp',
            'required'  =>  false
        ));
        $resolver->setRequired(
            array(
                'min',
                'max'
            )
        );
        $resolver->setOptional(
            array(
                'curMax',
                'curMin',
            )
        );
    }
    public function buildView(FormView $view, FormInterface $form, array $options)
    {
        parent::buildView($view, $form, $options);

        $curVal = explode(':', $view->vars['value']);
        if(!isset($options['curMin'])){
            $options['curMin'] = $options['min'];
        }
        if(!isset($options['curMax'])){
            $options['curMax'] = $options['max'];
        }
        $view->vars = array_merge(
            $view->vars,
            array(
                'curMax'    => count($curVal)>1? $curVal[1] : intval($options['curMax']),
                'curMin'    => count($curVal)>1? $curVal[0] : intval($options['curMin']),
                'max'       => intval($options['max']),
                'min'       => intval($options['min'])
            )
        );
    }
    /**
     * Returns the name of this type.
     *
     * @return string The name of this type
     */
    public function getName()
    {
        return "date_range";
    }

    public function getParent(){
        return 'text';
    }


}